In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
from statsmodels.stats import weightstats, proportion

### Questão 01
O índice de felicidade é uma métrica utilizada para mensurar o critério subjetivo "felicidade" nos diferentes países do globo. Utilizando o dataset 'happiness_2016', teste a hipótese de que as pessoas dos países da europa ocidental (Western Europe) são igualmente felizes às pessoas da América Latina e Caribe (Latin America and Caribbean). Nível de confiança: 95%.

H0: μ1 = μ2 \
Ha: μ1 ≠ μ2

In [20]:
df = pd.read_csv('happiness_2016.csv')
df.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [21]:
df['Region'].unique()

array(['Western Europe', 'North America', 'Australia and New Zealand',
       'Middle East and Northern Africa', 'Latin America and Caribbean',
       'Southeastern Asia', 'Central and Eastern Europe', 'Eastern Asia',
       'Sub-Saharan Africa', 'Southern Asia'], dtype=object)

In [22]:
df1 = df[df['Region'] == 'Western Europe']
df2 = df[df['Region'] == 'Latin America and Caribbean']

In [23]:
stats.ttest_ind(df1['Happiness Score'], df2['Happiness Score'], equal_var=True)

Ttest_indResult(statistic=2.5852641312418685, pvalue=0.01320479263961062)

Conclusão: \
Temos que pValue < 0.05, rejeitamos a hipótese nula. Portanto, as pessoas da Europa Ocidental e da América Latina e Caribe Não são igualmente felizes.

### Questão 02
Dinheiro traz felicidade? Para responder a essa pergunta, realize um teste de hipótese com os 20 países mais ricos e os 20 países mais pobres do relatório de felicidade de 2016. Use a coluna Economy (GDP per Capita). Nível de confiança: 95%.

H0: μ_ricos <= μ_pobres \
Ha: μ_ricos > μ_ricos \
OU \
H0: μ_pobres >= μ_ricos \
Ha: μ_pobres < μ_ricos

In [24]:
dfq2 = df.sort_values(by='Economy (GDP per Capita)')
df_pobres = dfq2.head(20)
df_ricos = dfq2.tail(20)

In [25]:
#H0: μ_ricos <= μ_pobres 
#Ha: μ_ricos > μ_ricos
stats.ttest_ind(df_ricos['Happiness Score'], df_pobres['Happiness Score'], equal_var=True, alternative='greater')

Ttest_indResult(statistic=15.832694378737427, pvalue=1.2744291831224112e-18)

In [26]:
#H0: μ_pobres >= μ_ricos 
#Ha: μ_pobres < μ_ricos
stats.ttest_ind(df_pobres['Happiness Score'], df_ricos['Happiness Score'], equal_var=True, alternative='less')

Ttest_indResult(statistic=-15.832694378737427, pvalue=1.2744291831224112e-18)

Conclusão: \
Temos que pValue < 0.05. Portanto, rejeitamos a hipótese nula: os países com maior renda per capita tem maior índice de felicidade. Assim, dinheiro traz sim felicidade de acordo com este teste de hipótese.

### Questão 03
Países que possuem índice de felicidade maior ou igual 5.5 são considerados países felizes. Uma pesquisa de 2006 mostrava que dos 24 países asiáticos consultados, 9 eram países felizes. Esse número aumentou em 2016, de acordo com o arquivo 'happiness_2016.csv'? Confiança: 95%.

H0: p_2006 >= p_2016 \
Ha: p_2006 < p_2016

In [27]:
df['Region'].unique()

array(['Western Europe', 'North America', 'Australia and New Zealand',
       'Middle East and Northern Africa', 'Latin America and Caribbean',
       'Southeastern Asia', 'Central and Eastern Europe', 'Eastern Asia',
       'Sub-Saharan Africa', 'Southern Asia'], dtype=object)

In [28]:
dfq3 = df[df['Region'].isin(['Southeastern Asia', 'Eastern Asia', 'Southern Asia'])]
dfq3_feliz = dfq3[dfq3['Happiness Score'] >= 5.5]

dfq3_feliz.count()

Country                          6
Region                           6
Happiness Rank                   6
Happiness Score                  6
Lower Confidence Interval        6
Upper Confidence Interval        6
Economy (GDP per Capita)         6
Family                           6
Health (Life Expectancy)         6
Freedom                          6
Trust (Government Corruption)    6
Generosity                       6
Dystopia Residual                6
dtype: int64

In [29]:
proportion.test_proportions_2indep(9, 24, 6, 22, method='score', alternative='smaller')

<class 'statsmodels.stats.base.HolderTuple'>
statistic = 0.7310659874497414
pvalue = 0.7676305758916229
compare = 'diff'
method = 'score'
variance = 0.01957070707070707
alternative = 'smaller'
prop1_null = 0.32608695652173914
prop2_null = 0.32608695652173914
tuple = (0.7310659874497414, 0.7676305758916229)
diff = 0.10227272727272729
ratio = 1.375
odds_ratio = 1.6
value = 0

Conclusão: \
Temos que pValue > 0.05. Portanto, falhamos em rejeitar a hipótese nula. Assim, o número de países felizes não aumentou em 2016.

### Questão 04
Os estudantes de uma determinada universidade fizeram duas provas da disciplina de estatística. O desempenho nessas provas é exibido no campos score1 e score2 do dataset 'students.csv'. Entre as provas foi oferecido um tutorial online de estatística. Realize um teste de hipótese que verifique se os alunos que realizaram o tutorial (online.tutorial = 1) tiveram uma melhora no desempenho na segunda avaliação (score2) em relação à primeira avaliação (score1). Confiança: 95%.

H0: μnota1 >= μnota2 \
Ha : μnota1 < μnota2

In [30]:
df = pd.read_csv('students.csv')
df.head()

,Unnamed: 0,stud.id,name,gender,age,height,weight,religion,nc.score,semester,major,minor,score1,score2,online.tutorial,graduated,salary
0,11,200803,"Lang, Mackenzie",Female,22,162,66.8,Other,1.04,4th,Economics and Finance,Environmental Sciences,62.0,61.0,1,1,45254.108021
1,13,354271,"Covar Orendain, Christopher",Male,23,185,84.6,Orthodox,1.00,4th,Environmental Sciences,Mathematics and Statistics,71.0,76.0,1,1,40552.790243
2,14,317812,"Lopez, Monique",Female,20,158,64.4,Catholic,2.50,6th,Environmental Sciences,Social Sciences,66.0,70.0,1,1,27007.030294
3,17,350040,"Hines, Haileigh",Female,22,156,61.7,Other,2.27,6th,Political Science,Biology,57.0,54.0,0,1,33969.159268
4,28,763393,"Woolsey, Bronson",Male,24,182,80.1,Protestant,1.09,5th,Economics and Finance,Social Sciences,61.0,73.0,1,1,50617.641870

In [31]:
df1 = df[df['online.tutorial'] == 1]
stats.ttest_rel(df1['score2'], df1['score1'], alternative='greater')
#OU
#stats.ttest_rel(df1['score1'], df1['score2'], alternative='less')

TtestResult(statistic=11.354028842990264, pvalue=1.0552920429884129e-28, df=1158)

Conclusão: \
Como pValue < 0.05 rejeitamos a hipótese nula. Os alunos que fizeram o tutorial melhoraram as notas na P2

### Questão 05
Deseja-se investigar se a religião do estudante tem algum impacto no seu desempenho acadêmico. Para tanto, realize um teste de hipótese nas notas do curso de estatística disponível no dataset 'students.csv' para as diferentes religões presentes no dataset. Para obter a nota final do curso, faça a média aritmética de score1 e score2 e salve em uma nova coluna chamada 'final.score'. Realize o teste com confiança de 95%.

H0: μ2 = μ3 = μ4 = μ4 = μ5 (média das notas são iguais) \
HA: médias das notas não são iguais

In [32]:
df['final.score'] = (df['score1'] + df['score2'])/2
df.head()

,Unnamed: 0,stud.id,name,gender,age,height,weight,religion,nc.score,semester,major,minor,score1,score2,online.tutorial,graduated,salary,final.score
0,11,200803,"Lang, Mackenzie",Female,22,162,66.8,Other,1.04,4th,Economics and Finance,Environmental Sciences,62.0,61.0,1,1,45254.108021,61.5
1,13,354271,"Covar Orendain, Christopher",Male,23,185,84.6,Orthodox,1.00,4th,Environmental Sciences,Mathematics and Statistics,71.0,76.0,1,1,40552.790243,73.5
2,14,317812,"Lopez, Monique",Female,20,158,64.4,Catholic,2.50,6th,Environmental Sciences,Social Sciences,66.0,70.0,1,1,27007.030294,68.0
3,17,350040,"Hines, Haileigh",Female,22,156,61.7,Other,2.27,6th,Political Science,Biology,57.0,54.0,0,1,33969.159268,55.5
4,28,763393,"Woolsey, Bronson",Male,24,182,80.1,Protestant,1.09,5th,Economics and Finance,Social Sciences,61.0,73.0,1,1,50617.641870,67.0

In [33]:
df['religion'].unique()

array(['Other', 'Orthodox', 'Catholic', 'Protestant', 'Muslim'],
      dtype=object)

In [34]:
df1 = df[df['religion'] == 'Other']
df2 = df[df['religion'] == 'Orthodox']
df3 = df[df['religion'] == 'Catholic']
df4 = df[df['religion'] == 'Protestant']
df5 = df[df['religion'] == 'Muslim']

In [35]:
stats.f_oneway(df1['final.score'], df2['final.score'],df3['final.score'],df4['final.score'],df5['final.score'])

F_onewayResult(statistic=0.6113048018162477, pvalue=0.6545273083263001)

Conclusão: \
Temos pValue > 0.05, portanto falhamos em rejeitar a hipótese nula. A média das notas não tem relação com a religião dos estudantes.

### Questão 06
Uma galeria de arte recebeu dois conjuntos de quadros (conjunto 1 e conjunto 2). O tamanho do quadro é definido pela medida da sua diagonal. Os arquivos 'quadros1.csv' e 'quadros2.csv' contém as medidas das diagonais dos conjuntos 1 e 2, respectivamente. De acordo com os dados contidos nesses arquivos, é possível dizer que o tamanho médio dos quadros dos dois conjuntos é o mesmo? Responda esta pergunta realizando um teste de hipótese.  Nível de confiança: 95%.

H0: μ1 = μ2 \
Ha: μ1 ≠ μ2

In [36]:
df1 = pd.read_csv('quadros1.csv')
df2 = pd.read_csv('quadros2.csv')
stats.ttest_ind(df1, df2, equal_var=False)

Ttest_indResult(statistic=array([-2.26324892]), pvalue=array([0.03282321]))

Como o valor de pvalue = 0.03 é menor que 0.05, temos que rejeitar a hipótese nula. Assim, a média dos tamanhos dos quadros NÃO é a mesma.