## Teste de uma proporção

Taxa de fumantes em uma cidade era 21%. Uma amostra de 100 habitantes encontrou 14 fumantes. A proporção de fumantes da cidade mudou (nível de confiança = 95%)?

In [67]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats

H0: p = p0 \
HA: p ≠ p0

In [68]:
stats.binomtest(14, 100, p=0.21, alternative='two-sided')

BinomTestResult(k=14, n=100, alternative='two-sided', statistic=0.14, pvalue=0.10920815720825927)

Como tivemos P Value > 0,05, falhamos em rejeitar a hipótese nula. Portanto, a proporção de fumantes NÃO mudou.

Taxa de fumantes em uma cidade era 21%. Uma amostra de 100 habitantes encontrou 14 fumantes. A proporção de fumantes da cidade reduziu? (uma cauda – nível de confiança = 95%).

H0: p >= p0 \
HA: p < p0

In [69]:
stats.binomtest(14, 100, p=0.21, alternative='less')

BinomTestResult(k=14, n=100, alternative='less', statistic=0.14, pvalue=0.05042460221552124)

Como tivemos P Value > 0,05, falhamos em rejeitar a hipótese nula. Portanto, a proporção de fumantes NÃO reduziu.

Exercício 1 \
Uma empresa realizou uma campanha anti-tabagismo visando diminuir a proporção de seus trabalhadores que são fumantes. Sabe-se que antes da campanha 21% dos trabalhadores se declaravam fumantes. Para verificar se essa porcentagem mudou após a campanha, a empresa coletou informações de 100 funcionários e armazenou o resultado no arquivo Smokers.csv. Realize um teste de hipótese e informe se a proporção de fumantes continua a mesma ou mudou.

In [70]:
df = pd.read_csv('Smokers.csv')
df.head()

       Name Smokers
0  Person 1      No
1  Person 2      No
2  Person 3      No
3  Person 4     Yes
4  Person 5      No

In [71]:
fumantes = df.groupby('Smokers').count()
fumantes

         Name
Smokers
No         83
Yes        17

In [72]:
nro_fumantes = fumantes.loc['Yes'].values[0]

In [73]:
stats.binomtest(nro_fumantes, 100, p=0.21, alternative='two-sided')

BinomTestResult(k=17, n=100, alternative='two-sided', statistic=0.17, pvalue=0.3900816892191665)

H0: p = p0 \
HA: p ≠ p0

Como P Value > 0,05, falhamos em rejeitar a hipótese nula. Portanto, a proporção de fumantes não mudou.

Exercício 2 \
Uma estimativa feita por um instuto de pesquisa apontou que 25% das mulheres que frequentam restaurantes numa dada cidade são fumantes. O dono de um restaurante decidiu testar uma amostra de suas clientes para verificar se esta estimativa é correta. Realize o teste de uma proporção com os dados contidos em 'tips.csv' e informe se a estimativa está correta (nível de confiança = 95%).

In [74]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [75]:
df2 = df[df['sex']=='Female']
df2 = df2[['sex', 'smoker']]
df2

        sex smoker
0    Female     No
4    Female     No
11   Female     No
14   Female     No
16   Female     No
..      ...    ...
226  Female    Yes
229  Female    Yes
238  Female     No
240  Female    Yes
243  Female     No

[87 rows x 2 columns]

In [76]:
fumantes = df2.groupby('smoker').count()
fumantes

        sex
smoker
Yes      33
No       54

In [77]:
nro_fumantes = fumantes.loc['Yes'].values[0]

In [78]:
stats.binomtest(nro_fumantes, 87, p=0.25, alternative='two-sided')

BinomTestResult(k=33, n=87, alternative='two-sided', statistic=0.3793103448275862, pvalue=0.008747732318429489)

H0: p = p0 \
HA: p ≠ p0

Como P Value < 0,05, rejeitamos a hipótese nula. Portanto, a proporção de fumantes é diferente de 25%.